### ISSUE TITLE
Get this error message every time I close Anki

### ISSUE THREAD

**Issue by yuyueshihaoren** [ssricardo/anki-web-browser#1]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (arch-linux-2.1.26-1) Python 3.8.3 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2020-06-24 21:10:16
Add-ons possibly involved: ⁨Web Browser - Search terms Import texts and images automatically⁩

Caught exception:
Traceback (most recent call last):
  File "/home/xxx/.local/share/Anki2/addons21/864545277/browser.py", line 104, in kloseBrowser
    return fn(evt)
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 973, in closeEvent
    self.unloadProfileAndExit()
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 436, in unloadProfileAndExit
    self.unloadProfile(self.cleanupAndExit)
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 411, in unloadProfile
    self.unloadCollection(callback)
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 519, in unloadCollection
    self.closeAllWindows(callback)
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 783, in closeAllWindows
    aqt.dialogs.closeAll(onsuccess)
  File "/usr/lib/python3.8/site-packages/aqt/__init__.py", line 108, in closeAll
    onsuccess()
  File "/usr/lib/python3.8/site-packages/aqt/main.py", line 515, in callback
    self.media_syncer.show_diag_until_finished()
  File "/usr/lib/python3.8/site-packages/aqt/mediasync.py", line 143, in show_diag_until_finished
    diag.exec_()
AttributeError: 'NoneType' object has no attribute 'exec_'
```
As the message shows, I'm on using Anki 2.1.26 with Python 3.8.3 and PyQt 5.15.0. I'm on Manjaro KDE Plasma.

This error does not affect normal use.

**Comment by ssricardo** [comment]
Thanks for reporting. I'll take a look

**Comment by ssricardo** [comment]
Handled (hopefully) on version 4.2
