### ISSUE TITLE
ModuleNotFoundError: No module named 'typing'

### ISSUE THREAD

**Issue by egalion** [ssricardo/anki-web-browser#16]
Hello, I get the following error after update (february 2022)

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Web Browser - Search terms Import texts and images automatically':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/home/user1/.local/share/Anki2/addons21/864545277/__init__.py", line 9, in <module>
    from .config import main
  File "/home/user1/.local/share/Anki2/addons21/864545277/config/main.py", line 8, in <module>
    from typing import List
ModuleNotFoundError: No module named 'typing'
```

**Comment by egalion** [comment]
I updated to the last version of Anki and the problem has been fixed.

**Comment by ssricardo** [comment]
Great that you already got it, thank you!
