### ISSUE TITLE
Crashed Anki after changing some things

### ISSUE THREAD

**Issue by darlopvil** [ssricardo/anki-web-browser#22]
Log showed by Anki. Addon needed to be unabled.

⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\__init__.py", line 34, in <module>
    run()
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\runner.py", line 58, in run
    controllerInstance = ReviewController(mw)
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\review_controller.py", line 30, in __init__
    super(ReviewController, self).__init__(ankiMw)
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\base_controller.py", line 26, in __init__
    self.browser = AwBrowser.singleton(ankiMw, cfg.getInitialWindowSize())
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\browser.py", line 90, in singleton
    cls.SINGLETON = AwBrowser(parent, sizeConfig)
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\browser.py", line 75, in __init__
    self.setupUI(sizingConfig)
  File "C:\Users\Usuario\AppData\Roaming\Anki2\addons21\864545277\browser.py", line 217, in setupUI
    self.setWindowFlags(Qt.WindowType.WindowType.WindowStaysOnTopHint)
AttributeError: sip.enumtype object 'WindowType' has no member 'WindowType'
⁩

**Comment by ssricardo** [comment]
Hi! I think you were using PyPQ6 already.

A new version was released which addresses PyQt 6.
Please, reopen this if the issue still happens after updating (and restarting)
