### ISSUE TITLE
Causes reviewew to not open

### ISSUE THREAD

**Issue by GreenPhenz** [ssricardo/anki-web-browser#26]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-13 12:35:44

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 662, in _onBridgeCmd
  File "aqt.overview", line 92, in _linkHandler
  File "aqt.main", line 712, in moveToState
  File "aqt.main", line 733, in _reviewState
  File "aqt.reviewer", line 161, in show
  File "aqt.reviewer", line 181, in refresh_if_needed
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
TypeError: my_next_card() got multiple values for argument '_old'

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-13 12:35:44

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 274, in on_focus_changed
  File "_aqt.hooks", line 3236, in __call__
  File "aqt.main", line 802, in on_focus_did_change
  File "aqt.reviewer", line 181, in refresh_if_needed
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
TypeError: my_next_card() got multiple values for argument '_old'

**Comment by ssricardo** [comment]
Hi!
I couldn't reproduce this.
I Tested (with Anki 2.1.65) on MacOS, Windows and Linux and it works fine on all of them.

So, I guess some other add-on which comes earlier in the chain might be breaking it, or sending the wrong values to the next add-on - the web-browser in this case.

I'll leave the issue for a little long to see if anyone else also faced that...
