### ISSUE TITLE
Addon gives error

### ISSUE THREAD

**Issue by CaptainDead** [ssricardo/anki-web-browser#30]
When I click on 'study' for a deck and sometimes by just opening anki, I get that error only once, for another error I will have to restart and click on 'study' again.
![image](https://github.com/ssricardo/anki-web-browser/assets/139457914/f1ff4cbd-5970-4637-89c1-4e1d05a823fe)

Copy debug info - 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.overview", line 97, in _linkHandler
  File "aqt.main", line 740, in moveToState
  File "aqt.main", line 761, in _reviewState
  File "aqt.reviewer", line 174, in show
  File "aqt.reviewer", line 194, in refresh_if_needed
  File "C:\Users\capta\AppData\Roaming\Anki2\addons21\864545277\review_controller.py", line 64, in wrapped
    originalResult = originalFunction(self)
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 84, in repl
  File "aqt.reviewer", line 252, in nextCard
  File "aqt.reviewer", line 395, in _showQuestion
  File "_aqt.hooks", line 4264, in __call__
  File "anki.hooks", line 34, in runHook
TypeError: 'NoneType' object is not callable

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T17:09, 'None', '']
Add Table ['1237621971', 2023-06-18T17:07, 'None', mod]
Advanced Review Bottom Bar ['1136455830', 2024-02-05T00:08, 'None', mod]
Always On Top - permanently keep Anki as top Fixed for Anki 23 by Shige ['1045980020', 2024-03-23T09:25, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-01-20T02:47, 'None', mod]
Anki Habitica for 21 ['1758045507', 2023-12-16T18:03, 'None', mod]
Anki Killstreaks - Reward Medals for Correct Answers - Fixed by Shige ['1562475180', 2024-03-14T16:16, 'None', mod]
AnkiDraw - Draw and write using mouse and stylus with pressure support ['1868980340', 2024-04-04T23:50, 'None', '']
AnkiRestart Quick Aniki Rebooter for Anki Customize and Develop by Shige ['237169833', 2024-02-06T18:51, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-28T00:56, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-03-26T20:11, 'None', mod]
Answer visual  auditory  custom text reinforcement ['976516370', 2023-11-21T22:15, 'None', mod]
Browser Card Info Bar ['2140680811', 2024-04-05T16:09, 'None', mod]
Browser external editor -  open separate window - Fixed for Anki 23 by Shige ['1284875472', 2024-03-05T10:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T13:57, 'None', '']
Color Confirmation ['1084228676', 2024-01-06T15:25, 'None', mod]
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T20:36, 'None', '']
Confirm deletion of the card in Reviewer Fixed for Anki24 by Shige ['354810378', 2024-04-07T18:06, 'None', '']
Congrats Confetti ['206062158', 2023-01-17T09:32, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T17:20, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T06:49, 'None', mod]
Deck Browser CSS - Fixed for Anki 23 by Shige ['996212191', 2024-03-05T19:19, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-22T00:47, 'None', '']
Image Editor ['307397307', 2022-09-08T09:39, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T23:30, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-04-11T16:05, 'None', mod]
More Overview Stats 21 ['738807903', 2021-07-31T00:43, 'None', '']
No Distractions Full Screen Fixed for Anki 23 by Shige ['1370336700', 2024-03-05T18:55, 'None', mod]
OpenInExternalEditorRenameDuplicate for ImageAudioVideo WinLinux ['1560623518', 2023-03-19T23:03, 'None', '']
Pokemanki Gold - Raising Pokemon with Anki Fork for Anki23 by Shige ['1677779223', 2024-03-29T22:15, 'None', mod]
Preview Slideshow Fork for Anki 23 by Shige ['1621302762', 2024-01-13T18:27, 'None', mod]
Progress bar Fixed for Anki 24 by Shige ['1708250053', 2024-04-08T20:40, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T18:29, 'None', mod]
Random Sprites - Find new random image on cards Fixed for Anki 23 by Shige ['1956685960', 2024-02-15T11:09, 'None', '']
ReColor ['688199788', 2024-03-03T07:15, '3.0', mod]
Remove card history ['2089200096', 2023-10-19T08:45, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T07:13, 'None', '']
Review Lookup ['1745211643', 2022-06-22T12:42, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-20T03:02, 'None', '']
Simple Timer and Stopwatch Fixed for Anki24 by Shige ['2041168053', 2024-04-08T16:27, 'None', '']
Spell Checker ['369581638', 2023-10-11T19:17, 'None', '']
Study Time Stats ['1247171202', 2024-02-24T22:29, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T11:12, 'None', '']
TidyAnkiBear - Select and hide Anki menu bar items by Shige ['906950015', 2024-02-12T05:28, 'None', mod]
Undelete deleted note ['912930620', 2022-03-04T05:10, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-18T00:58, 'None', mod]
Zoom 23 - Keep zoom level after reboot Fixed for Anki 23 by Shige ['1923741581', 2024-02-22T02:27, 'None', mod]
add-on dialog searchfilter bar ['561945101', 2023-10-18T21:52, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T19:42, 'None', mod]
link Cards Notes and Preview them in extra window ['1423933177', 2023-10-28T03:56, 'None', '']

===IDs of active AnkiWeb add-ons===
1045980020 1084228676 1136455830 1143540799 1210908941 1237621971 1247171202 1284875472 1370336700 1423933177 1556734708 1560623518 1562475180 1621302762 1677779223 1708250053 1722658993 1745211643 1758045507 1771074083 1868980340 1906641654 1908235722 1923741581 1956685960 2040501954 2041168053 206062158 2089200096 2140680811 225180905 237169833 272311064 295889520 307397307 31746032 318752047 354810378 369581638 561945101 594329229 688199788 738807903 805891399 864545277 906950015 912930620 952691989 976516370 996212191

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Deck name in title 21 ['699175524', 2019-06-01T06:35, 'None', '']
Motivanki ['663438166', 2022-06-23T21:08, 'None', mod]
No Space Dash-Prevents answer for 15 seconds-Fixed for Anki 23 by Shige ['1573867049', 2024-02-26T20:51, '20.12.25i94', '']

**Comment by ssricardo** [comment]
The integration with Anki was changed, to (hopefully) avoid these issues.
